apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: umami-start
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  envFrom:
  - secret: umami-bigquery
  liveness:
    path: /isalive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://startumami.ansatt.dev.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no # bytte til trygdeetaten.no ?
    sidecar:
      autoLogin: true
      enabled: true